using System.Text.Json.Serialization;

namespace TodoApi.Models
{
    public class Contact
    {
        /// <summary>
        /// This is the id property
        /// </summary>
        [JsonPropertyName("id")]
        public int Id { get; set; }

        // Modify to string? so .net doesn't validate the field
        [JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// This is autogenerated, do not pass it to me.
        /// </summary>
        [JsonPropertyName("date_added")]
        public DateTime DateAdded { get; set; }
    }
}
